apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pac-backend.fullname" . }}
  labels:
    {{- include "pac-backend.labels" . | nindent 4 }}
data:
  application.yaml: |-
    spring:
      data:
        neo4j:
          uri: {{ .Values.neo4j.uri }} 
    client.url: {{ .Values.client.uri }}