keycloak:
  ingress:
    enabled: true
    hosts:
      - keycloak.minikube
  persistence:
    dbVendor: mariadb
    dbPort: 3306
  service:
    type: NodePort
    httpNodePort: 32020
    httpsNodePort: 32021