server:
  port: 8080
  servlet:    context-path: /api
spring:
  application:
    name: pac-backend
  cloud:
    kubernetes:
      discovery:
        enabled: true
      reload:
        enabled: false
      config:
        enabled: true
  data:
    neo4j:
      uri: bolt://minikube:32011
      username: neo4j
      password: pacneo4j
management:  endpoints:    web:      exposure:        include: info, health, metrics
  endpoint:    health:      show-details: ALWAYS
  health:    neo4j:      enabled: true
client.url: http://localhost:8081