server:
  port: 8080
  servlet:    context-path: /api
spring:
  application:
    name: pac-backend
  cloud:
    kubernetes:
      discovery:
        enabled: true
      reload:
        enabled: false
      config:
        enabled: true
  data:
    neo4j:
      uri: bolt://minikube:32011
      username: ${DATABASE_USERNAME:neo4j}
      password: ${DATABASE_PASSWORD:pacneo4j}  main:    allow-bean-definition-overriding: true
management:  endpoints:    web:      exposure:        include: info, health, metrics, prometheus
  endpoint:    health:      show-details: ALWAYS
    metrics:      enabled: true
    prometheus:      enabled: true
  metrics:    export:      prometheus:        enabled: true        step: 30s
  health:      
    neo4j:      enabled: true
client.url: http://localhost:8081
keycloak:  auth-server-url: http://minikube:32020/auth/
  realm: pac
  resource: pac-backend
  bearer-only: true
  principal-attribute: preferred_username
# auth-server-url: http://keycloak.minikube/auth/
# auth-server-url: http://keycloak-http.keycloak/auth/